            - name: Cloudflare Pages GitHub Action
  # You may pin to the exact commit or the version.
  # uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca
  uses: cloudflare/pages-action@v1.5.0
  with:
    # Cloudflare API Token
    apiToken: 
    # Cloudflare Account ID
    accountId: 
    # The name of the Pages project to upload to
    projectName: 
    # The directory of static assets to upload
    directory: 
    # GitHub Token
    gitHubToken: # optional
    # The name of the branch you want to deploy to
    branch: # optional
    # The working directory in which to run Wrangler
    workingDirectory: # optional
    # The version of Wrangler to use
    wranglerVersion: # optional, default is 2
          
